/**
 * Mock marketplace data for development/testing.
 * Provides prebuilt agents and skills listings + full definitions.
 */

import type {
    IAgentDefinitionDTO,
    ISkillDefinitionDTO,
    IAgentMarketplaceListingDTO,
    ISkillMarketplaceListingDTO,
} from '@agenthub/contracts'

// ─── Prebuilt Skill Definitions ─────────────────────────────────────────────

export const MOCK_SKILL_DEFINITIONS: readonly ISkillDefinitionDTO[] = [
    {
        id: 'skill-web-search',
        name: 'Web Search',
        version: '1.2.0',
        description: 'Search the web using multiple search engines and aggregate results into structured summaries.',
        requiredCapabilities: ['network.fetch', 'ai.generate'],
        permissions: ['network.fetch', 'ai.generate'],
        tools: [
            {
                name: 'web_search',
                description: 'Perform a web search and return top results',
                inputSchema: { type: 'object', properties: { query: { type: 'string' }, maxResults: { type: 'number' } }, required: ['query'] },
                timeoutMs: 15000,
                requiredCapabilities: ['network.fetch'],
            },
            {
                name: 'summarize_results',
                description: 'Summarize search results with AI',
                inputSchema: { type: 'object', properties: { results: { type: 'array' }, format: { type: 'string' } }, required: ['results'] },
                timeoutMs: 30000,
                requiredCapabilities: ['ai.generate'],
            },
        ],
        category: 'productivity',
        author: 'AgentHub Team',
        icon: '🔍',
        tags: ['search', 'web', 'research'],
        signature: 'agenthub-verified-sig-001',
        createdAt: '2025-11-01T00:00:00Z',
        updatedAt: '2026-01-15T00:00:00Z',
    },
    {
        id: 'skill-code-analysis',
        name: 'Code Analysis',
        version: '2.0.0',
        description: 'Analyze code repositories for quality, security vulnerabilities, and performance bottlenecks.',
        requiredCapabilities: ['ai.generate', 'computer.files'],
        permissions: ['ai.generate', 'computer.files'],
        tools: [
            {
                name: 'analyze_code',
                description: 'Analyze a code file or directory',
                inputSchema: { type: 'object', properties: { path: { type: 'string' }, language: { type: 'string' } }, required: ['path'] },
                timeoutMs: 60000,
                requiredCapabilities: ['computer.files', 'ai.generate'],
            },
            {
                name: 'security_scan',
                description: 'Scan code for security vulnerabilities',
                inputSchema: { type: 'object', properties: { path: { type: 'string' } }, required: ['path'] },
                timeoutMs: 120000,
                requiredCapabilities: ['computer.files', 'ai.generate'],
            },
        ],
        category: 'developer',
        author: 'AgentHub Team',
        icon: '🔬',
        tags: ['code', 'analysis', 'security', 'quality'],
        signature: 'agenthub-verified-sig-002',
        createdAt: '2025-10-15T00:00:00Z',
        updatedAt: '2026-02-01T00:00:00Z',
    },
    {
        id: 'skill-data-visualization',
        name: 'Data Visualization',
        version: '1.0.0',
        description: 'Generate charts, graphs, and data visualizations from structured data.',
        requiredCapabilities: ['ai.generate', 'storage.read'],
        permissions: ['ai.generate', 'storage.read'],
        tools: [
            {
                name: 'create_chart',
                description: 'Create a chart from data',
                inputSchema: { type: 'object', properties: { data: { type: 'array' }, chartType: { type: 'string' }, title: { type: 'string' } }, required: ['data', 'chartType'] },
                timeoutMs: 30000,
                requiredCapabilities: ['ai.generate'],
            },
        ],
        category: 'creative',
        author: 'DataViz Labs',
        icon: '📊',
        tags: ['data', 'charts', 'visualization'],
        createdAt: '2025-12-01T00:00:00Z',
    },
    {
        id: 'skill-email-compose',
        name: 'Email Composer',
        version: '1.1.0',
        description: 'Draft professional emails based on context, tone, and recipient analysis.',
        requiredCapabilities: ['ai.generate', 'memory.read'],
        permissions: ['ai.generate', 'memory.read'],
        tools: [
            {
                name: 'compose_email',
                description: 'Compose an email based on instructions',
                inputSchema: { type: 'object', properties: { to: { type: 'string' }, subject: { type: 'string' }, context: { type: 'string' }, tone: { type: 'string' } }, required: ['to', 'subject', 'context'] },
                timeoutMs: 20000,
                requiredCapabilities: ['ai.generate'],
            },
        ],
        category: 'productivity',
        author: 'CommTools Inc',
        icon: '✉️',
        tags: ['email', 'writing', 'communication'],
        signature: 'commtools-sig-001',
        createdAt: '2025-09-20T00:00:00Z',
        updatedAt: '2026-01-10T00:00:00Z',
    },
    {
        id: 'skill-file-manager',
        name: 'File Manager',
        version: '1.3.0',
        description: 'Manage, organize, and search through local files with AI-powered categorization.',
        requiredCapabilities: ['computer.files', 'ai.generate', 'filesystem'],
        permissions: ['computer.files', 'ai.generate', 'filesystem'],
        tools: [
            {
                name: 'search_files',
                description: 'Search files by name, content, or metadata',
                inputSchema: { type: 'object', properties: { query: { type: 'string' }, directory: { type: 'string' } }, required: ['query'] },
                timeoutMs: 30000,
                requiredCapabilities: ['computer.files'],
            },
            {
                name: 'organize_files',
                description: 'Organize files into structured directories',
                inputSchema: { type: 'object', properties: { sourceDir: { type: 'string' }, strategy: { type: 'string' } }, required: ['sourceDir'] },
                timeoutMs: 60000,
                requiredCapabilities: ['computer.files', 'filesystem'],
            },
        ],
        category: 'utilities',
        author: 'AgentHub Team',
        icon: '📁',
        tags: ['files', 'organization', 'search'],
        signature: 'agenthub-verified-sig-003',
        createdAt: '2025-11-20T00:00:00Z',
        updatedAt: '2026-02-10T00:00:00Z',
    },
    {
        id: 'skill-memory-manager',
        name: 'Memory Manager',
        version: '1.0.0',
        description: 'Manage long-term memory, session context, and knowledge retrieval for agents.',
        requiredCapabilities: ['memory.read', 'memory.write'],
        permissions: ['memory.read', 'memory.write'],
        tools: [
            {
                name: 'store_memory',
                description: 'Store information in agent memory',
                inputSchema: { type: 'object', properties: { key: { type: 'string' }, value: { type: 'string' }, scope: { type: 'string' } }, required: ['key', 'value'] },
                timeoutMs: 5000,
                requiredCapabilities: ['memory.write'],
            },
            {
                name: 'recall_memory',
                description: 'Recall information from agent memory',
                inputSchema: { type: 'object', properties: { query: { type: 'string' }, scope: { type: 'string' } }, required: ['query'] },
                timeoutMs: 5000,
                requiredCapabilities: ['memory.read'],
            },
        ],
        category: 'utilities',
        author: 'AgentHub Team',
        icon: '🧠',
        tags: ['memory', 'context', 'knowledge'],
        signature: 'agenthub-verified-sig-004',
        createdAt: '2025-12-15T00:00:00Z',
    },
]

// ─── Prebuilt Agent Definitions ─────────────────────────────────────────────

export const MOCK_AGENT_DEFINITIONS: readonly IAgentDefinitionDTO[] = [
    {
        id: 'agent-research-assistant',
        name: 'Research Assistant',
        version: '2.1.0',
        description: 'A comprehensive research agent that searches the web, analyzes documents, and produces structured research reports with citations.',
        capabilities: ['ai.generate', 'ai.stream', 'network.fetch', 'memory.read', 'memory.write', 'storage.read'],
        permissions: ['ai.generate', 'ai.stream', 'network.fetch', 'memory.read', 'memory.write', 'storage.read'],
        memoryConfig: {
            enabled: true,
            scopes: ['working', 'session', 'long-term'],
            maxEntriesPerScope: 500,
            persistAcrossSessions: true,
        },
        tools: [
            {
                name: 'research_plan',
                description: 'Create a research plan based on a topic',
                inputSchema: { type: 'object', properties: { topic: { type: 'string' }, depth: { type: 'string' } }, required: ['topic'] },
                timeoutMs: 30000,
            },
        ],
        skills: [MOCK_SKILL_DEFINITIONS[0]!, MOCK_SKILL_DEFINITIONS[5]!],
        author: 'AgentHub Team',
        icon: '🔬',
        category: 'productivity',
        tags: ['research', 'analysis', 'web'],
        maxTokenBudget: 500000,
        systemPrompt: 'You are a thorough research assistant. Always cite sources and provide structured outputs.',
        model: 'gpt-4',
        signature: 'agenthub-verified-sig-100',
        createdAt: '2025-09-01T00:00:00Z',
        updatedAt: '2026-02-15T00:00:00Z',
    },
    {
        id: 'agent-code-reviewer',
        name: 'Code Reviewer',
        version: '1.5.0',
        description: 'Automated code review agent that checks for bugs, security issues, performance problems, and code style violations.',
        capabilities: ['ai.generate', 'ai.stream', 'computer.files', 'filesystem', 'memory.read', 'memory.write'],
        permissions: ['ai.generate', 'ai.stream', 'computer.files', 'filesystem', 'memory.read', 'memory.write'],
        memoryConfig: {
            enabled: true,
            scopes: ['working', 'session'],
            maxEntriesPerScope: 200,
            persistAcrossSessions: false,
        },
        tools: [],
        skills: [MOCK_SKILL_DEFINITIONS[1]!],
        author: 'AgentHub Team',
        icon: '👨‍💻',
        category: 'developer',
        tags: ['code', 'review', 'quality', 'security'],
        maxTokenBudget: 300000,
        systemPrompt: 'You are a senior code reviewer. Focus on correctness, security, and clean code practices.',
        model: 'gpt-4',
        signature: 'agenthub-verified-sig-101',
        createdAt: '2025-10-01T00:00:00Z',
        updatedAt: '2026-01-20T00:00:00Z',
    },
    {
        id: 'agent-writing-assistant',
        name: 'Writing Assistant',
        version: '1.0.0',
        description: 'Professional writing assistant for drafting emails, reports, blog posts, and other content with tone-awareness.',
        capabilities: ['ai.generate', 'ai.stream', 'memory.read', 'memory.write', 'storage.read'],
        permissions: ['ai.generate', 'ai.stream', 'memory.read', 'memory.write', 'storage.read'],
        memoryConfig: {
            enabled: true,
            scopes: ['working', 'session'],
            maxEntriesPerScope: 100,
            persistAcrossSessions: false,
        },
        tools: [],
        skills: [MOCK_SKILL_DEFINITIONS[3]!],
        author: 'CommTools Inc',
        icon: '✍️',
        category: 'creative',
        tags: ['writing', 'email', 'content'],
        maxTokenBudget: 200000,
        systemPrompt: 'You are an expert writer. Adapt your tone and style based on the target audience.',
        model: 'gpt-4',
        createdAt: '2025-11-15T00:00:00Z',
    },
    {
        id: 'agent-data-analyst',
        name: 'Data Analyst',
        version: '1.2.0',
        description: 'Analyze datasets, generate visualizations, and produce data-driven insights with statistical analysis.',
        capabilities: ['ai.generate', 'ai.stream', 'storage.read', 'storage.write', 'memory.read', 'memory.write'],
        permissions: ['ai.generate', 'ai.stream', 'storage.read', 'storage.write', 'memory.read', 'memory.write'],
        memoryConfig: {
            enabled: true,
            scopes: ['working', 'session', 'long-term'],
            maxEntriesPerScope: 1000,
            persistAcrossSessions: true,
        },
        tools: [
            {
                name: 'analyze_data',
                description: 'Run statistical analysis on a dataset',
                inputSchema: { type: 'object', properties: { data: { type: 'array' }, analysis: { type: 'string' } }, required: ['data'] },
                timeoutMs: 60000,
            },
        ],
        skills: [MOCK_SKILL_DEFINITIONS[2]!],
        author: 'DataViz Labs',
        icon: '📈',
        category: 'productivity',
        tags: ['data', 'analysis', 'statistics', 'visualization'],
        maxTokenBudget: 400000,
        systemPrompt: 'You are a data analyst. Provide clear statistical insights and actionable recommendations.',
        model: 'gpt-4',
        signature: 'dataviz-sig-100',
        createdAt: '2025-12-01T00:00:00Z',
        updatedAt: '2026-02-01T00:00:00Z',
    },
    {
        id: 'agent-devops-helper',
        name: 'DevOps Helper',
        version: '1.0.0',
        description: 'DevOps assistant that helps with CI/CD pipelines, infrastructure management, and deployment automation.',
        capabilities: ['ai.generate', 'computer.shell', 'computer.files', 'filesystem', 'network.fetch', 'memory.read', 'memory.write'],
        permissions: ['ai.generate', 'computer.shell', 'computer.files', 'filesystem', 'network.fetch', 'memory.read', 'memory.write'],
        memoryConfig: {
            enabled: true,
            scopes: ['working', 'session'],
            maxEntriesPerScope: 300,
            persistAcrossSessions: false,
        },
        tools: [
            {
                name: 'run_pipeline',
                description: 'Execute a CI/CD pipeline step',
                inputSchema: { type: 'object', properties: { command: { type: 'string' }, env: { type: 'object' } }, required: ['command'] },
                timeoutMs: 300000,
                requiredCapabilities: ['computer.shell'],
            },
        ],
        skills: [MOCK_SKILL_DEFINITIONS[4]!],
        author: 'AgentHub Team',
        icon: '🚀',
        category: 'developer',
        tags: ['devops', 'ci-cd', 'deployment', 'infrastructure'],
        maxTokenBudget: 250000,
        systemPrompt: 'You are a DevOps assistant. Follow security best practices and always explain actions before executing.',
        model: 'gpt-4',
        signature: 'agenthub-verified-sig-102',
        createdAt: '2026-01-01T00:00:00Z',
    },
]

// ─── Marketplace Listings ───────────────────────────────────────────────────

export const MOCK_AGENT_LISTINGS: readonly IAgentMarketplaceListingDTO[] = MOCK_AGENT_DEFINITIONS.map((a) => ({
    id: a.id,
    type: 'agent' as const,
    name: a.name,
    version: a.version,
    description: a.description,
    author: a.author ?? 'Unknown',
    category: a.category ?? 'general',
    tags: [...(a.tags ?? [])],
    icon: a.icon,
    downloadCount: Math.floor(Math.random() * 10000) + 500,
    rating: Math.round((3.5 + Math.random() * 1.5) * 10) / 10,
    verified: !!a.signature,
    signature: a.signature,
    publishedAt: a.createdAt ?? new Date().toISOString(),
    capabilities: [...a.capabilities],
    skillCount: a.skills.length,
    toolCount: a.tools.length + a.skills.reduce((sum, s) => sum + s.tools.length, 0),
}))

export const MOCK_SKILL_LISTINGS: readonly ISkillMarketplaceListingDTO[] = MOCK_SKILL_DEFINITIONS.map((s) => ({
    id: s.id,
    type: 'skill' as const,
    name: s.name,
    version: s.version,
    description: s.description,
    author: s.author ?? 'Unknown',
    category: s.category,
    tags: [...(s.tags ?? [])],
    icon: s.icon,
    downloadCount: Math.floor(Math.random() * 8000) + 300,
    rating: Math.round((3.5 + Math.random() * 1.5) * 10) / 10,
    verified: !!s.signature,
    signature: s.signature,
    publishedAt: s.createdAt ?? new Date().toISOString(),
    requiredCapabilities: [...s.requiredCapabilities],
    toolCount: s.tools.length,
}))
