export { createRuntime } from './factory.js'
export type { IRuntimeConfig, IRuntimeBundle } from './factory.js'
export type { IDependencyContainer } from './container.js'
export { createDesktopPlatform } from './desktop-extension.js'
export type { IDesktopPlatformConfig, IDesktopPlatformBundle } from './desktop-extension.js'
