import React from 'react'
import { Badge, Card, SectionTitle } from './settings-shared.js'

export function AboutTab({ version }: { version: string }): React.JSX.Element {
  const isDev = Boolean(import.meta.env.DEV)

  return (
    <div className="space-y-5">
      {/* App identity */}
      <Card>
        <div className="flex items-center gap-4 border-b border-[var(--color-border)] px-4 py-4">
          <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-gradient-to-br from-[var(--color-accent)] to-purple-600 text-xl shadow-lg">
            🤖
          </div>
          <div>
            <p className="text-sm font-semibold text-[var(--color-text-primary)]">AgentHub</p>
            <p className="text-xs text-[var(--color-text-muted)]">Your real AI assistant</p>
            <div className="mt-1.5 flex items-center gap-1.5">
              <Badge variant={isDev ? 'warning' : 'success'}>{isDev ? '⚡ Development' : '🚀 Production'}</Badge>
              <Badge>v{version}</Badge>
            </div>
          </div>
        </div>
        <div className="divide-y divide-[var(--color-border)]">
          {[
            { label: 'Version',        value: version },
            { label: 'Runtime',        value: 'Tauri 2 + Rust' },
            { label: 'UI',             value: 'React 18 + TypeScript' },
            { label: 'State',          value: 'Zustand' },
            { label: 'Local DB',       value: 'SQLite (via Tauri)' },
            { label: 'Architecture',   value: 'Agent on device + Cloud Gateway' },
          ].map(({ label, value }) => (
            <div key={label} className="flex items-center justify-between px-4 py-2.5">
              <span className="text-xs text-[var(--color-text-muted)]">{label}</span>
              <span className="text-xs font-medium text-[var(--color-text-primary)]">{value}</span>
            </div>
          ))}
        </div>
      </Card>

      {/* Links */}
      <div>
        <SectionTitle>Resources</SectionTitle>
        <Card>
          {[
            { label: 'Documentation',    icon: '📖', href: 'https://docs.agenthub.com' },
            { label: 'GitHub Repository', icon: '⬡',  href: 'https://github.com/agenthub/desktop' },
            { label: 'Report an issue',  icon: '🐛', href: 'https://github.com/agenthub/desktop/issues' },
            { label: 'Release notes',    icon: '📋', href: 'https://github.com/agenthub/desktop/releases' },
          ].map(({ label, icon, href }, i, arr) => (
            <a
              key={label}
              href={href}
              target="_blank"
              rel="noopener noreferrer"
              className={`flex items-center justify-between px-4 py-3 transition-colors hover:bg-[var(--color-surface-2)] ${i < arr.length - 1 ? 'border-b border-[var(--color-border)]' : ''}`}
            >
              <div className="flex items-center gap-2.5">
                <span className="text-sm">{icon}</span>
                <span className="text-xs font-medium text-[var(--color-text-primary)]">{label}</span>
              </div>
              <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" className="text-[var(--color-text-muted)]">
                <line x1="7" y1="17" x2="17" y2="7"/><polyline points="7 7 17 7 17 17"/>
              </svg>
            </a>
          ))}
        </Card>
      </div>

      {/* Legal */}
      <div>
        <SectionTitle>Legal</SectionTitle>
        <Card>
          <div className="px-4 py-3 text-[11px] leading-relaxed text-[var(--color-text-muted)]">
            AgentHub Desktop is open-source software released under the MIT License.
            AI responses are generated by third-party providers. We are not responsible for
            AI-generated content. Use responsibly.
          </div>
        </Card>
      </div>
    </div>
  )
}
